@extends('layouts.app')

@section('content')
    <div class="entry-content clearfix">
        <h3></h3>
        <div id="toc_container" class="toc_wrap_right no_bullets"><p class="toc_title">Content Overview <span class="toc_toggle">[<a href="#">hide</a>]</span></p><ul class="toc_list"><li><a href="#Terms_of_use"><span class="toc_number toc_depth_1">1</span> Terms of use</a></li><li><a href="#Updatein_Privacy_Policy"><span class="toc_number toc_depth_1">2</span> Update&nbsp;in Privacy Policy</a></li><li><a href="#Data_Sharing"><span class="toc_number toc_depth_1">3</span> Data Sharing</a></li><li><a href="#Cookies"><span class="toc_number toc_depth_1">4</span> Cookies</a></li><li><a href="#Source_code_Copyrights"><span class="toc_number toc_depth_1">5</span> Source code Copyrights</a></li><li><a href="#Analytics_Advertisement"><span class="toc_number toc_depth_1">6</span> Analytics &amp; &nbsp;Advertisement</a></li><li><a href="#We_don8217t_collect"><span class="toc_number toc_depth_1">7</span> We don’t collect</a></li><li><a href="#We_collect"><span class="toc_number toc_depth_1">8</span> We collect</a></li></ul></div>
        <h3><span id="Terms_of_use"><strong>Terms of use</strong></span></h3>
        <p>If you are using <a href="http://satoshi.com" target="_blank" rel="noopener"><strong>satoshi</strong> </a>website then you must accept this privacy policy. If not then please check out all the details of this website’s <strong>Privacy Policy</strong>. Otherwise, it is considered that you are accepting and you do not have any kind of objections against it.</p>
        <p>&nbsp;</p>
        <h3><span id="Updatein_Privacy_Policy"><strong>Update&nbsp;in Privacy Policy</strong></span></h3> command r sxmi
        <p><strong>Privacy Policy</strong> of <strong>satoshi</strong> is subject to change without any prior notice to visitors. <strong>satoshi&nbsp;</strong>can update this privacy <strong>Privacy Policy</strong> as and when required.</p>
        <p>&nbsp;</p>
        <div class="bsac bsac-clearfix bsac-post-inline bsac-float-center bsac-align-center bsac-column-1"><div id="bsac-2805-1289088387" class="bsac-container bsac-type-code " itemscope="" itemtype="https://schema.org/WPAdBlock" data-adid="2805" data-type="code"><a itemprop="url" class="bsac-link" href="" target="_blank"><img class="bsac-image" src="" alt="Large Rectangle Middle"></a></div></div> <h3><span id="Data_Sharing"><strong>Data Sharing</strong></span></h3>
        <p>We don’t share your personal information with other or any external parties. We only collect the data to improve our service via collecting feedbacks of&nbsp;<strong>our site</strong></p>
        <p>If you find our article very useful or if you find any issues regarding our articles then you can contact us via comment section and for the comment, you need to give your name, email and website information to the&nbsp;<strong>satoshi</strong></p>
        <p>Again,&nbsp;We don’t share your personal information with other or any external parties.</p>
        <p>&nbsp;</p>
        <div class="bsac bsac-clearfix bsac-post-middle bsac-float-center bsac-align-center bsac-column-1"><div id="bsac-2806-663810090" class="bsac-container bsac-type-code " itemscope="" itemtype="https://schema.org/WPAdBlock" data-adid="2806" data-type="code"><span id="bsac-2806-663810090-place"></span><script type="text/javascript">var betterads_screen_width = document.body.clientWidth;betterads_el = document.getElementById('bsac-2806-663810090');             if (betterads_el.getBoundingClientRect().width) {     betterads_el_width_raw = betterads_el_width = betterads_el.getBoundingClientRect().width;    } else {     betterads_el_width_raw = betterads_el_width = betterads_el.offsetWidth;    }        var size = ["125", "125"];    if ( betterads_el_width >= 728 )      betterads_el_width = ["728", "90"];    else if ( betterads_el_width >= 468 )     betterads_el_width = ["468", "60"];    else if ( betterads_el_width >= 336 )     betterads_el_width = ["336", "280"];    else if ( betterads_el_width >= 300 )     betterads_el_width = ["300", "250"];    else if ( betterads_el_width >= 250 )     betterads_el_width = ["250", "250"];    else if ( betterads_el_width >= 200 )     betterads_el_width = ["200", "200"];    else if ( betterads_el_width >= 180 )     betterads_el_width = ["180", "150"]; if ( betterads_screen_width >= 1140 ) {          document.getElementById('bsac-2806-663810090-place').innerHTML = '';          (adsbygoogle = window.adsbygoogle || []).push({});         }else if ( betterads_screen_width >= 1019  && betterads_screen_width < 1140 ) { document.getElementById('bsac-2806-663810090-place').innerHTML = '';         (adsbygoogle = window.adsbygoogle || []).push({});}else if ( betterads_screen_width >= 768  && betterads_screen_width < 1019 ) { document.getElementById('bsac-2806-663810090-place').innerHTML = '';         (adsbygoogle = window.adsbygoogle || []).push({});}else if ( betterads_screen_width < 768 ) { document.getElementById('bsac-2806-663810090-place').innerHTML = '';         (adsbygoogle = window.adsbygoogle || []).push({});}</script></div></div> <h3><span id="Cookies"><strong>Cookies</strong></span></h3>
        <p>Cookies are created by your Web browser. We use Cookies to enhance the user experience of&nbsp;<strong>satoshi</strong>. We never place personally identifiable information in Cookies. Additionally, our business partners (for example, advertisers) may use cookies as well. <strong>Our website</strong>&nbsp;has no access or control of advertiser’s web cookies and is not responsible for any information stored in these types of cookies. Visitors can disable the use of cookies by changing settings of their respective web browser. However, if you disable Cookies, there might be chances that you can not access contents on our Website effectively or at all.</p>
        <p>&nbsp;</p>
        <div class="bsac bsac-clearfix bsac-post-inline bsac-float-center bsac-align-center bsac-column-1"><div id="bsac-3228-1672189818" class="bsac-container bsac-type-code " itemscope="" itemtype="https://schema.org/WPAdBlock" data-adid="3228" data-type="code"><a itemprop="url" class="bsac-link" href="" target="_blank"><img class="bsac-image" src="" alt="ADSENSE_MIDDLE_POST_1"></a></div></div> <h3><span id="Source_code_Copyrights"><strong>Source code Copyrights</strong></span></h3>
        <p>All the contents and source code downloaded from this blog is the property of&nbsp;<strong>satoshi</strong> and can be used for personal education purpose only. Visitors are not allowed to use, copy or repost the source code to any business or commercial blogs. All the content <strong>C</strong><strong>opyrights</strong> are held by&nbsp;<strong>satoshi.</strong></p>
        <p>&nbsp;</p>
        <h3><span id="Analytics_Advertisement"><strong>Analytics &amp; &nbsp;Advertisement</strong></span></h3>
        <p>We are using following tools to track the user information and advertisement.</p>
        <p><b>Google Analytics:&nbsp;</b>Track User Information.</p>
        <p>&nbsp;</p>
        <h3><span id="We_don8217t_collect">We don’t collect</span></h3>
        <p><strong>satoshi&nbsp;</strong>does not collect information like contact number, credit/debit card details or other banking details from any visitor.</p>
        <p>&nbsp;</p>
        <div class="bsac bsac-clearfix bsac-post-inline bsac-float-center bsac-align-center bsac-column-1"><div id="bsac-3229-529388169" class="bsac-container bsac-type-code " itemscope="" itemtype="https://schema.org/WPAdBlock" data-adid="3229" data-type="code"><a itemprop="url" class="bsac-link" href="" target="_blank"><img class="bsac-image" src="" alt="ADSENSE_MIDDLE_POST_2"></a></div></div> <h3><span id="We_collect">We collect</span></h3>
        <p><strong>satoshi&nbsp;</strong>collect personally identifiable information such as name, email address, and website.</p> 			</div>
@endsection
